# Project Information
site_name: ARO Workshop Atlanta
<<<<<<< HEAD
site_url: https://ws.mobb.cloud/
site_description: A choose-your-own-adventure workshop for Operations and Development teams on ARO.
=======
site_url: https://michaelryanmcneill.github.io/aro-hackathon-content
site_description: A for Operations and Development teams on ARO.
>>>>>>> a78436f (initial v2)
site_author: Red Hat

# Repository
repo_name: michaelryanmcneill/aro-hackathon-content
repo_url: https://github.com/michaelryanmcneill/aro-hackathon-content

# Nav Menu Definition
nav:
<<<<<<< HEAD
  - Welcome: index.md
  - Environment Setup: setup/environment.md
  - Access Your Cluster: setup/access-cluster.md
  - Day Two ARO Operations:
    - Managing Cluster Upgrades: ops/day2/upgrades.md
    - Managing Worker Nodes: ops/day2/scaling-nodes.md
    - Cluster Autoscaling: ops/day2/autoscaling.md
    - Labeling Nodes: ops/day2/labels.md
  - Azure Service Operator (ASO):
    - Deploy the Azure Service Operator: ops/aso/deploy.md
    - Deploy an Azure Service using ASO: ops/aso/app.md
  - Azure Front Door:
    - Create a Private Ingress Controller: ops/afd/private-ingress.md
    - Configure Azure Front Door: ops/afd/configure.md
  - Deploy and Expose an App:
    - Deploy the App: app/deploy.md
    - Expose the App with Front Door: app/afd.md
    - Automate Deploying the App: app/cicd.md
  - Make an App Resilient: app/resilience.md
  - Azure Arc: 
    - Connect Azure Arc with ARO: ops/arc/integration.md
    - Enable Azure Arc Observability: ops/arc/observability.md
    - Integrate Azure Key Vault: ops/arc/key-vault.md
  - Service Mesh:
    - Service Mesh: service-mesh/introduction.md
    - Deploy Service Mesh Operator: service-mesh/install.md
    - Deploy Control Plane: service-mesh/deploy-control-plane.md
    - Deploy Workloads: service-mesh/deploy-workload.md
    - Deploy Weighted Load Balancing: service-mesh/weighted-routing.md
    - Access Kiali Dashboard: service-mesh/kiali.md
=======
  - index.md
  - Workshop Setup: general/1-workshop-setup.md
  - Getting Started
    - Create an ARO Cluster: ops/1-1-create-cluster.md
    - Retieve Cluster Credentials: ops/1-3-get-credentials.md
  - Prepare the Cluster and Evironment
    - Install Pipelines and Service Mesh Operators
      - Deploy Pipeline Operator: ops/2-1-operators.md
      - Deploy Service Mesh Operator: service-meshv2/0-infrastructure_operator_install.md
    - Label Nodes: ops/2-4-label-nodes.md
    - Azure Service Operator: ops/3-deploy-azure-service-operator.md
    - Deploy Cosmos Database: ops/2-5-deploy-cosmos-aso.md
    - Azure ARC Integration: ops/5-arc-integration.md
  - Managing Worker Nodes: ops/2-2-worker-nodes.md
  - Deploy an Application
    - Deploy the frontend: app/2-1-deploy-frontend.md
    - Deploy the backend: app/2-2-deploy-backend.md
    - Test the application app/2-3-test-app.md
  - Make the application resilent
    - Setup cluster autoscaling: ops/2-3-autoscaling.md
    - Make Applications Resilient 
        - Scale the application: app/3-scale-app.md
        - Create a Pod Disruption Budget: app/3-scale-app.md
        - Scale down the application: app/3-scale-app.md
  - Exposing Applications:
    - Create a private ingress controller: app/4-private-ingress.md
    - Create Azure Front Door Service: ops/5-frontdoor.md
    - Expose the application: app/2A-deploy-app.md
  - Automate Deploying an Application
    - Automate Deploying the App: app/2C-deploy-app.md
  - Advanced Application Configuration with Service Mesh
      - Introduction: service-meshv2/00-introduction.md
      - Deploy Weighted Load Balancing: service-meshv2/3-weighted-routing.md
      - Access Kiali Dashboard: service-meshv2/access_kiali_dashboard.md
  - ARO Day X Operations:
      - Managing Upgrades: ops/2-1-upgrades.md
    

>>>>>>> a78436f (initial v2)


# Theme Configuration
theme:
  features:
    - content.code.annotate
  name: material
  language: 'en'
  palette:
    primary: black
    accent: red
  font:
    text: Overpass
    code: Overpass Mono
  logo: favicon.ico
  favicon: favicon.ico
docs_dir: aro-content

# Extensions
markdown_extensions:
  - abbr
  - toc:
      permalink: "#"
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: 'aro-content/assets/'

# Google Analytics
