# Project Information
site_name: ARO Workshop Atlanta
site_url: https://ws.mobb.cloud/
site_description: A choose-your-own-adventure workshop for Operations and Development teams on ARO.
site_author: Red Hat

# Repository
repo_name: rh-mobb/aro-hackathon-content
repo_url: https://github.com/rh-mobb/aro-hackathon-content

# Nav Menu Definition
nav:
  - Welcome: index.md
  - Environment Setup: 100-setup/1-environment.md
  - Create ARO Cluster: 100-setup/2-cluster-creation.md
  - Access Your Cluster: 100-setup/3-access-cluster.md
  - Day Two ARO Operations:
    - Managing Cluster Upgrades: 200-ops/day2/upgrades.md
    - Managing Worker Nodes: 200-ops/day2/scaling-nodes.md
    - Cluster Autoscaling: 200-ops/day2/autoscaling.md
    - Labeling Nodes: 200-ops/day2/labels.md
  # - Azure Service Operator (ASO):
  #   - Deploy the Azure Service Operator: 200-ops/aso/deploy.md
  #   - Deploy an Azure Service using ASO: 200-ops/aso/app.md
  # - Azure Front Door:
  #   - Create a Private Ingress Controller: 200-ops/afd/private-ingress.md
  #   - Configure Azure Front Door: 200-ops/afd/configure.md
  - Deploy and Expose an App:
    - Deploy the App: 300-app/deploy.md
    # - Expose the App with Front Door: 300-app/afd.md
    - Automate Deploying the App: 300-app/cicd.md
  - Make an App Resilient: 300-app/resilience.md
  # - Azure Arc:
  #   - Connect Azure Arc with ARO: 400-cluster-mgmt/arc/integration.md
  #   - Enable Azure Arc Observability: 400-cluster-mgmt/arc/observability.md
  #   - Integrate Azure Key Vault: 400-cluster-mgmt/arc/key-vault.md
  - Service Mesh:
    - Service Mesh: 500-service-mesh/introduction.md
    - Deploy Service Mesh Operator: 500-service-mesh/install.md
    - Deploy Control Plane: 500-service-mesh/deploy-control-plane.md
    - Deploy Workloads: 500-service-mesh/deploy-workload.md
    - Deploy Weighted Load Balancing: 500-service-mesh/weighted-routing.md
    - Access Kiali Dashboard: 500-service-mesh/kiali.md


# Theme Configuration
theme:
  features:
    - content.code.annotate
  name: material
  language: 'en'
  palette:
    primary: black
    accent: red
  font:
    text: Overpass
    code: Overpass Mono
  logo: favicon.ico
  favicon: favicon.ico
docs_dir: aro-content

# plugins
plugins:
- section-index

# Extensions
markdown_extensions:
  - abbr
  - toc:
      permalink: "#"
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: 'aro-content/assets/'

extra_css:
  - assets/css/custom.css

# Google Analytics
